name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run Go test
      run: go test -v ./...
